/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Bangumi/': RouteRecordInfo<
      '/Bangumi/',
      '/Bangumi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/love/': RouteRecordInfo<
      '/love/',
      '/love',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/love/MIKU': RouteRecordInfo<
      '/love/MIKU',
      '/love/MIKU',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/love/Nachoneko': RouteRecordInfo<
      '/love/Nachoneko',
      '/love/Nachoneko',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/love/SIKADI': RouteRecordInfo<
      '/love/SIKADI',
      '/love/SIKADI',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/love/WX': RouteRecordInfo<
      '/love/WX',
      '/love/WX',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/love/ZFB': RouteRecordInfo<
      '/love/ZFB',
      '/love/ZFB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bios-boot-animation-change': RouteRecordInfo<
      '/posts/bios-boot-animation-change',
      '/posts/bios-boot-animation-change',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/blog-deploy-live2d-vercount': RouteRecordInfo<
      '/posts/blog-deploy-live2d-vercount',
      '/posts/blog-deploy-live2d-vercount',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bypass-wifi-auth-3xui-tunnel-fzbz': RouteRecordInfo<
      '/posts/bypass-wifi-auth-3xui-tunnel-fzbz',
      '/posts/bypass-wifi-auth-3xui-tunnel-fzbz',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/centos-dns-config': RouteRecordInfo<
      '/posts/centos-dns-config',
      '/posts/centos-dns-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/comments-miscellaneous': RouteRecordInfo<
      '/posts/comments-miscellaneous',
      '/posts/comments-miscellaneous',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/custom-typora-background': RouteRecordInfo<
      '/posts/custom-typora-background',
      '/posts/custom-typora-background',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/data-sim-guide': RouteRecordInfo<
      '/posts/data-sim-guide',
      '/posts/data-sim-guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/default': RouteRecordInfo<
      '/posts/default',
      '/posts/default',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/directory-opus': RouteRecordInfo<
      '/posts/directory-opus',
      '/posts/directory-opus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/docker-compose-configs': RouteRecordInfo<
      '/posts/docker-compose-configs',
      '/posts/docker-compose-configs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/docker-install-usage': RouteRecordInfo<
      '/posts/docker-install-usage',
      '/posts/docker-install-usage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/domain-blocked-by-isp-not-gfw': RouteRecordInfo<
      '/posts/domain-blocked-by-isp-not-gfw',
      '/posts/domain-blocked-by-isp-not-gfw',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Email': RouteRecordInfo<
      '/posts/Email',
      '/posts/Email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/fix-npm-pnpm-update-issue': RouteRecordInfo<
      '/posts/fix-npm-pnpm-update-issue',
      '/posts/fix-npm-pnpm-update-issue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/free-vps-clawcloudrun-3xui-tunnel': RouteRecordInfo<
      '/posts/free-vps-clawcloudrun-3xui-tunnel',
      '/posts/free-vps-clawcloudrun-3xui-tunnel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/frp-config': RouteRecordInfo<
      '/posts/frp-config',
      '/posts/frp-config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/FZBZF': RouteRecordInfo<
      '/posts/FZBZF',
      '/posts/FZBZF',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Game': RouteRecordInfo<
      '/posts/Game',
      '/posts/Game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/grub2-config-theme-windows': RouteRecordInfo<
      '/posts/grub2-config-theme-windows',
      '/posts/grub2-config-theme-windows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hackbgrt-windows-boot-animation': RouteRecordInfo<
      '/posts/hackbgrt-windows-boot-animation',
      '/posts/hackbgrt-windows-boot-animation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hardware-log': RouteRecordInfo<
      '/posts/hardware-log',
      '/posts/hardware-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/intel-mac-maa-arknights': RouteRecordInfo<
      '/posts/intel-mac-maa-arknights',
      '/posts/intel-mac-maa-arknights',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/l4d2-frp-low-latency': RouteRecordInfo<
      '/posts/l4d2-frp-low-latency',
      '/posts/l4d2-frp-low-latency',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/lethal-company-lan-server': RouteRecordInfo<
      '/posts/lethal-company-lan-server',
      '/posts/lethal-company-lan-server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/LSPosedIT': RouteRecordInfo<
      '/posts/LSPosedIT',
      '/posts/LSPosedIT',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/markdown-typora-guide': RouteRecordInfo<
      '/posts/markdown-typora-guide',
      '/posts/markdown-typora-guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mtoolbox-windows-beautification': RouteRecordInfo<
      '/posts/mtoolbox-windows-beautification',
      '/posts/mtoolbox-windows-beautification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mydockfinder-mac-style': RouteRecordInfo<
      '/posts/mydockfinder-mac-style',
      '/posts/mydockfinder-mac-style',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/openlist-css-beautification': RouteRecordInfo<
      '/posts/openlist-css-beautification',
      '/posts/openlist-css-beautification',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/PoorBadminton': RouteRecordInfo<
      '/posts/PoorBadminton',
      '/posts/PoorBadminton',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/reading-pen-wifi-hotspot-auto-start': RouteRecordInfo<
      '/posts/reading-pen-wifi-hotspot-auto-start',
      '/posts/reading-pen-wifi-hotspot-auto-start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/software-auto-startup': RouteRecordInfo<
      '/posts/software-auto-startup',
      '/posts/software-auto-startup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/some-gugu-jpg': RouteRecordInfo<
      '/posts/some-gugu-jpg',
      '/posts/some-gugu-jpg',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/steamautocrack-usage': RouteRecordInfo<
      '/posts/steamautocrack-usage',
      '/posts/steamautocrack-usage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/valaxy-music-player': RouteRecordInfo<
      '/posts/valaxy-music-player',
      '/posts/valaxy-music-player',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/vercount-replace-busuanzi-valaxy': RouteRecordInfo<
      '/posts/vercount-replace-busuanzi-valaxy',
      '/posts/vercount-replace-busuanzi-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/vmware-25h2-download-chinese': RouteRecordInfo<
      '/posts/vmware-25h2-download-chinese',
      '/posts/vmware-25h2-download-chinese',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Web-Log': RouteRecordInfo<
      '/posts/Web-Log',
      '/posts/Web-Log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/xiaomi-band-heart-rate-obs': RouteRecordInfo<
      '/posts/xiaomi-band-heart-rate-obs',
      '/posts/xiaomi-band-heart-rate-obs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/xiaomi-be6500-ssh-shellcrash': RouteRecordInfo<
      '/posts/xiaomi-be6500-ssh-shellcrash',
      '/posts/xiaomi-be6500-ssh-shellcrash',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/xiaomi-fcm-root': RouteRecordInfo<
      '/posts/xiaomi-fcm-root',
      '/posts/xiaomi-fcm-root',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zerotyping-typing-website': RouteRecordInfo<
      '/posts/zerotyping-typing-website',
      '/posts/zerotyping-typing-website',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/status/': RouteRecordInfo<
      '/status/',
      '/status',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/update/': RouteRecordInfo<
      '/update/',
      '/update',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.4_mag_b8aac48cfe0a00ef180c350c958dd5a3/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.4_@babel+parser_91b5a8e5a76273ed0767438577afd8be/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/Bangumi/index.md': {
      routes:
        | '/Bangumi/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'pages/love/index.md': {
      routes:
        | '/love/'
      views:
        | never
    }
    'pages/love/MIKU.md': {
      routes:
        | '/love/MIKU'
      views:
        | never
    }
    'pages/love/Nachoneko.md': {
      routes:
        | '/love/Nachoneko'
      views:
        | never
    }
    'pages/love/SIKADI.md': {
      routes:
        | '/love/SIKADI'
      views:
        | never
    }
    'pages/love/WX.md': {
      routes:
        | '/love/WX'
      views:
        | never
    }
    'pages/love/ZFB.md': {
      routes:
        | '/love/ZFB'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.4_mag_b8aac48cfe0a00ef180c350c958dd5a3/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.4_mag_b8aac48cfe0a00ef180c350c958dd5a3/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/bios-boot-animation-change.md': {
      routes:
        | '/posts/bios-boot-animation-change'
      views:
        | never
    }
    'pages/posts/blog-deploy-live2d-vercount.md': {
      routes:
        | '/posts/blog-deploy-live2d-vercount'
      views:
        | never
    }
    'pages/posts/bypass-wifi-auth-3xui-tunnel-fzbz.md': {
      routes:
        | '/posts/bypass-wifi-auth-3xui-tunnel-fzbz'
      views:
        | never
    }
    'pages/posts/centos-dns-config.md': {
      routes:
        | '/posts/centos-dns-config'
      views:
        | never
    }
    'pages/posts/comments-miscellaneous.md': {
      routes:
        | '/posts/comments-miscellaneous'
      views:
        | never
    }
    'pages/posts/custom-typora-background.md': {
      routes:
        | '/posts/custom-typora-background'
      views:
        | never
    }
    'pages/posts/data-sim-guide.md': {
      routes:
        | '/posts/data-sim-guide'
      views:
        | never
    }
    'pages/posts/default.md': {
      routes:
        | '/posts/default'
      views:
        | never
    }
    'pages/posts/directory-opus.md': {
      routes:
        | '/posts/directory-opus'
      views:
        | never
    }
    'pages/posts/docker-compose-configs.md': {
      routes:
        | '/posts/docker-compose-configs'
      views:
        | never
    }
    'pages/posts/docker-install-usage.md': {
      routes:
        | '/posts/docker-install-usage'
      views:
        | never
    }
    'pages/posts/domain-blocked-by-isp-not-gfw.md': {
      routes:
        | '/posts/domain-blocked-by-isp-not-gfw'
      views:
        | never
    }
    'pages/posts/Email.md': {
      routes:
        | '/posts/Email'
      views:
        | never
    }
    'pages/posts/fix-npm-pnpm-update-issue.md': {
      routes:
        | '/posts/fix-npm-pnpm-update-issue'
      views:
        | never
    }
    'pages/posts/free-vps-clawcloudrun-3xui-tunnel.md': {
      routes:
        | '/posts/free-vps-clawcloudrun-3xui-tunnel'
      views:
        | never
    }
    'pages/posts/frp-config.md': {
      routes:
        | '/posts/frp-config'
      views:
        | never
    }
    'pages/posts/FZBZF.md': {
      routes:
        | '/posts/FZBZF'
      views:
        | never
    }
    'pages/posts/Game.md': {
      routes:
        | '/posts/Game'
      views:
        | never
    }
    'pages/posts/grub2-config-theme-windows.md': {
      routes:
        | '/posts/grub2-config-theme-windows'
      views:
        | never
    }
    'pages/posts/hackbgrt-windows-boot-animation.md': {
      routes:
        | '/posts/hackbgrt-windows-boot-animation'
      views:
        | never
    }
    'pages/posts/hardware-log.md': {
      routes:
        | '/posts/hardware-log'
      views:
        | never
    }
    'pages/posts/intel-mac-maa-arknights.md': {
      routes:
        | '/posts/intel-mac-maa-arknights'
      views:
        | never
    }
    'pages/posts/l4d2-frp-low-latency.md': {
      routes:
        | '/posts/l4d2-frp-low-latency'
      views:
        | never
    }
    'pages/posts/lethal-company-lan-server.md': {
      routes:
        | '/posts/lethal-company-lan-server'
      views:
        | never
    }
    'pages/posts/LSPosedIT.md': {
      routes:
        | '/posts/LSPosedIT'
      views:
        | never
    }
    'pages/posts/markdown-typora-guide.md': {
      routes:
        | '/posts/markdown-typora-guide'
      views:
        | never
    }
    'pages/posts/mtoolbox-windows-beautification.md': {
      routes:
        | '/posts/mtoolbox-windows-beautification'
      views:
        | never
    }
    'pages/posts/mydockfinder-mac-style.md': {
      routes:
        | '/posts/mydockfinder-mac-style'
      views:
        | never
    }
    'pages/posts/openlist-css-beautification.md': {
      routes:
        | '/posts/openlist-css-beautification'
      views:
        | never
    }
    'pages/posts/PoorBadminton.md': {
      routes:
        | '/posts/PoorBadminton'
      views:
        | never
    }
    'pages/posts/reading-pen-wifi-hotspot-auto-start.md': {
      routes:
        | '/posts/reading-pen-wifi-hotspot-auto-start'
      views:
        | never
    }
    'pages/posts/software-auto-startup.md': {
      routes:
        | '/posts/software-auto-startup'
      views:
        | never
    }
    'pages/posts/some-gugu-jpg.md': {
      routes:
        | '/posts/some-gugu-jpg'
      views:
        | never
    }
    'pages/posts/steamautocrack-usage.md': {
      routes:
        | '/posts/steamautocrack-usage'
      views:
        | never
    }
    'pages/posts/valaxy-music-player.md': {
      routes:
        | '/posts/valaxy-music-player'
      views:
        | never
    }
    'pages/posts/vercount-replace-busuanzi-valaxy.md': {
      routes:
        | '/posts/vercount-replace-busuanzi-valaxy'
      views:
        | never
    }
    'pages/posts/vmware-25h2-download-chinese.md': {
      routes:
        | '/posts/vmware-25h2-download-chinese'
      views:
        | never
    }
    'pages/posts/Web-Log.md': {
      routes:
        | '/posts/Web-Log'
      views:
        | never
    }
    'pages/posts/xiaomi-band-heart-rate-obs.md': {
      routes:
        | '/posts/xiaomi-band-heart-rate-obs'
      views:
        | never
    }
    'pages/posts/xiaomi-be6500-ssh-shellcrash.md': {
      routes:
        | '/posts/xiaomi-be6500-ssh-shellcrash'
      views:
        | never
    }
    'pages/posts/xiaomi-fcm-root.md': {
      routes:
        | '/posts/xiaomi-fcm-root'
      views:
        | never
    }
    'pages/posts/zerotyping-typing-website.md': {
      routes:
        | '/posts/zerotyping-typing-website'
      views:
        | never
    }
    'pages/status/index.md': {
      routes:
        | '/status/'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
    'pages/update/index.md': {
      routes:
        | '/update/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
