/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Bangumi/': RouteRecordInfo<
      '/Bangumi/',
      '/Bangumi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/love/': RouteRecordInfo<
      '/love/',
      '/love',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/love/MIKU': RouteRecordInfo<
      '/love/MIKU',
      '/love/MIKU',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/love/Nachoneko': RouteRecordInfo<
      '/love/Nachoneko',
      '/love/Nachoneko',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/love/SIKADI': RouteRecordInfo<
      '/love/SIKADI',
      '/love/SIKADI',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/love/WX': RouteRecordInfo<
      '/love/WX',
      '/love/WX',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/love/ZFB': RouteRecordInfo<
      '/love/ZFB',
      '/love/ZFB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/一些咕咕咕JPG': RouteRecordInfo<
      '/posts/一些咕咕咕JPG',
      '/posts/%E4%B8%80%E4%BA%9B%E5%92%95%E5%92%95%E5%92%95JPG',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/一些DockerCompose配置': RouteRecordInfo<
      '/posts/一些DockerCompose配置',
      '/posts/%E4%B8%80%E4%BA%9BDockerCompose%E9%85%8D%E7%BD%AE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/主板BIOS开机动画更改': RouteRecordInfo<
      '/posts/主板BIOS开机动画更改',
      '/posts/%E4%B8%BB%E6%9D%BFBIOS%E5%BC%80%E6%9C%BA%E5%8A%A8%E7%94%BB%E6%9B%B4%E6%94%B9',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/使用Vercount替代不蒜子 - Valaxy': RouteRecordInfo<
      '/posts/使用Vercount替代不蒜子 - Valaxy',
      '/posts/%E4%BD%BF%E7%94%A8Vercount%E6%9B%BF%E4%BB%A3%E4%B8%8D%E8%92%9C%E5%AD%90%20-%20Valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/免费VPSClawCloudRun使用3XUI面板进行隧道搭建': RouteRecordInfo<
      '/posts/免费VPSClawCloudRun使用3XUI面板进行隧道搭建',
      '/posts/%E5%85%8D%E8%B4%B9VPSClawCloudRun%E4%BD%BF%E7%94%A83XUI%E9%9D%A2%E6%9D%BF%E8%BF%9B%E8%A1%8C%E9%9A%A7%E9%81%93%E6%90%AD%E5%BB%BA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/关于Steam AutoCrack的使用方法': RouteRecordInfo<
      '/posts/关于Steam AutoCrack的使用方法',
      '/posts/%E5%85%B3%E4%BA%8ESteam%20AutoCrack%E7%9A%84%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/域名被运营商阻断而不是被GFWGank': RouteRecordInfo<
      '/posts/域名被运营商阻断而不是被GFWGank',
      '/posts/%E5%9F%9F%E5%90%8D%E8%A2%AB%E8%BF%90%E8%90%A5%E5%95%86%E9%98%BB%E6%96%AD%E8%80%8C%E4%B8%8D%E6%98%AF%E8%A2%ABGFWGank',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/如何自定义Typora的背景': RouteRecordInfo<
      '/posts/如何自定义Typora的背景',
      '/posts/%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89Typora%E7%9A%84%E8%83%8C%E6%99%AF',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/如何让想要的软件在开机的时候自动启动': RouteRecordInfo<
      '/posts/如何让想要的软件在开机的时候自动启动',
      '/posts/%E5%A6%82%E4%BD%95%E8%AE%A9%E6%83%B3%E8%A6%81%E7%9A%84%E8%BD%AF%E4%BB%B6%E5%9C%A8%E5%BC%80%E6%9C%BA%E7%9A%84%E6%97%B6%E5%80%99%E8%87%AA%E5%8A%A8%E5%90%AF%E5%8A%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/小米手环910 开启心率广播 投屏OBS直播': RouteRecordInfo<
      '/posts/小米手环910 开启心率广播 投屏OBS直播',
      '/posts/%E5%B0%8F%E7%B1%B3%E6%89%8B%E7%8E%AF910%20%E5%BC%80%E5%90%AF%E5%BF%83%E7%8E%87%E5%B9%BF%E6%92%AD%20%E6%8A%95%E5%B1%8FOBS%E7%9B%B4%E6%92%AD',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/小米BE6500开SSH开机自启固化和安装ShellCrash开启全家代理': RouteRecordInfo<
      '/posts/小米BE6500开SSH开机自启固化和安装ShellCrash开启全家代理',
      '/posts/%E5%B0%8F%E7%B1%B3BE6500%E5%BC%80SSH%E5%BC%80%E6%9C%BA%E8%87%AA%E5%90%AF%E5%9B%BA%E5%8C%96%E5%92%8C%E5%AE%89%E8%A3%85ShellCrash%E5%BC%80%E5%90%AF%E5%85%A8%E5%AE%B6%E4%BB%A3%E7%90%86',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/模版': RouteRecordInfo<
      '/posts/模版',
      '/posts/%E6%A8%A1%E7%89%88',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/求生之路2之使用FRP反代获得低延迟体验': RouteRecordInfo<
      '/posts/求生之路2之使用FRP反代获得低延迟体验',
      '/posts/%E6%B1%82%E7%94%9F%E4%B9%8B%E8%B7%AF2%E4%B9%8B%E4%BD%BF%E7%94%A8FRP%E5%8F%8D%E4%BB%A3%E8%8E%B7%E5%BE%97%E4%BD%8E%E5%BB%B6%E8%BF%9F%E4%BD%93%E9%AA%8C',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/流量卡-授人以鱼不如授人以渔': RouteRecordInfo<
      '/posts/流量卡-授人以鱼不如授人以渔',
      '/posts/%E6%B5%81%E9%87%8F%E5%8D%A1-%E6%8E%88%E4%BA%BA%E4%BB%A5%E9%B1%BC%E4%B8%8D%E5%A6%82%E6%8E%88%E4%BA%BA%E4%BB%A5%E6%B8%94',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/点读笔-如何在开机时自动启动WIFI热点': RouteRecordInfo<
      '/posts/点读笔-如何在开机时自动启动WIFI热点',
      '/posts/%E7%82%B9%E8%AF%BB%E7%AC%94-%E5%A6%82%E4%BD%95%E5%9C%A8%E5%BC%80%E6%9C%BA%E6%97%B6%E8%87%AA%E5%8A%A8%E5%90%AF%E5%8A%A8WIFI%E7%83%AD%E7%82%B9',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/硬件日志': RouteRecordInfo<
      '/posts/硬件日志',
      '/posts/%E7%A1%AC%E4%BB%B6%E6%97%A5%E5%BF%97',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/绕过WiFi的Web认证使用3XUI面板搭建隧道FZBZ': RouteRecordInfo<
      '/posts/绕过WiFi的Web认证使用3XUI面板搭建隧道FZBZ',
      '/posts/%E7%BB%95%E8%BF%87WiFi%E7%9A%84Web%E8%AE%A4%E8%AF%81%E4%BD%BF%E7%94%A83XUI%E9%9D%A2%E6%9D%BF%E6%90%AD%E5%BB%BA%E9%9A%A7%E9%81%93FZBZ',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/致命公司自建局域网服务器，反代联机（破解）': RouteRecordInfo<
      '/posts/致命公司自建局域网服务器，反代联机（破解）',
      '/posts/%E8%87%B4%E5%91%BD%E5%85%AC%E5%8F%B8%E8%87%AA%E5%BB%BA%E5%B1%80%E5%9F%9F%E7%BD%91%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%8C%E5%8F%8D%E4%BB%A3%E8%81%94%E6%9C%BA%EF%BC%88%E7%A0%B4%E8%A7%A3%EF%BC%89',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/解决npm或pnpm无法更新的问题': RouteRecordInfo<
      '/posts/解决npm或pnpm无法更新的问题',
      '/posts/%E8%A7%A3%E5%86%B3npm%E6%88%96pnpm%E6%97%A0%E6%B3%95%E6%9B%B4%E6%96%B0%E7%9A%84%E9%97%AE%E9%A2%98',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/评论杂烩QAQ': RouteRecordInfo<
      '/posts/评论杂烩QAQ',
      '/posts/%E8%AF%84%E8%AE%BA%E6%9D%82%E7%83%A9QAQ',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/需ROOT小米使用FCM(谷歌推送服务)': RouteRecordInfo<
      '/posts/需ROOT小米使用FCM(谷歌推送服务)',
      '/posts/%E9%9C%80ROOT%E5%B0%8F%E7%B1%B3%E4%BD%BF%E7%94%A8FCM(%E8%B0%B7%E6%AD%8C%E6%8E%A8%E9%80%81%E6%9C%8D%E5%8A%A1)',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/BLOG更新日志': RouteRecordInfo<
      '/posts/BLOG更新日志',
      '/posts/BLOG%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/BLOG网页部署live2d小人 - 使用Vercount替代不蒜子 - Valaxy': RouteRecordInfo<
      '/posts/BLOG网页部署live2d小人 - 使用Vercount替代不蒜子 - Valaxy',
      '/posts/BLOG%E7%BD%91%E9%A1%B5%E9%83%A8%E7%BD%B2live2d%E5%B0%8F%E4%BA%BA%20-%20%E4%BD%BF%E7%94%A8Vercount%E6%9B%BF%E4%BB%A3%E4%B8%8D%E8%92%9C%E5%AD%90%20-%20Valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CentOS配置DNS': RouteRecordInfo<
      '/posts/CentOS配置DNS',
      '/posts/CentOS%E9%85%8D%E7%BD%AEDNS',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Directory Opus': RouteRecordInfo<
      '/posts/Directory Opus',
      '/posts/Directory%20Opus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Docker的下载安装和使用': RouteRecordInfo<
      '/posts/Docker的下载安装和使用',
      '/posts/Docker%E7%9A%84%E4%B8%8B%E8%BD%BD%E5%AE%89%E8%A3%85%E5%92%8C%E4%BD%BF%E7%94%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Email': RouteRecordInfo<
      '/posts/Email',
      '/posts/Email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/FRP配置': RouteRecordInfo<
      '/posts/FRP配置',
      '/posts/FRP%E9%85%8D%E7%BD%AE',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/FZBZ-F': RouteRecordInfo<
      '/posts/FZBZ-F',
      '/posts/FZBZ-F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Game': RouteRecordInfo<
      '/posts/Game',
      '/posts/Game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/GRUB2配置以及自定义主题以及添加Windows引导': RouteRecordInfo<
      '/posts/GRUB2配置以及自定义主题以及添加Windows引导',
      '/posts/GRUB2%E9%85%8D%E7%BD%AE%E4%BB%A5%E5%8F%8A%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%BB%E9%A2%98%E4%BB%A5%E5%8F%8A%E6%B7%BB%E5%8A%A0Windows%E5%BC%95%E5%AF%BC',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/HackBGRT更改Windows开机动画': RouteRecordInfo<
      '/posts/HackBGRT更改Windows开机动画',
      '/posts/HackBGRT%E6%9B%B4%E6%94%B9Windows%E5%BC%80%E6%9C%BA%E5%8A%A8%E7%94%BB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Intel MAC使用MAA进行明日方舟挂机': RouteRecordInfo<
      '/posts/Intel MAC使用MAA进行明日方舟挂机',
      '/posts/Intel%20MAC%E4%BD%BF%E7%94%A8MAA%E8%BF%9B%E8%A1%8C%E6%98%8E%E6%97%A5%E6%96%B9%E8%88%9F%E6%8C%82%E6%9C%BA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MarkdownTypora的基本用法与常用操作': RouteRecordInfo<
      '/posts/MarkdownTypora的基本用法与常用操作',
      '/posts/MarkdownTypora%E7%9A%84%E5%9F%BA%E6%9C%AC%E7%94%A8%E6%B3%95%E4%B8%8E%E5%B8%B8%E7%94%A8%E6%93%8D%E4%BD%9C',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MToolBox 枫の美化工具箱 - Win美化的集大成者': RouteRecordInfo<
      '/posts/MToolBox 枫の美化工具箱 - Win美化的集大成者',
      '/posts/MToolBox%20%E6%9E%AB%E3%81%AE%E7%BE%8E%E5%8C%96%E5%B7%A5%E5%85%B7%E7%AE%B1%20-%20Win%E7%BE%8E%E5%8C%96%E7%9A%84%E9%9B%86%E5%A4%A7%E6%88%90%E8%80%85',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MydockFinder MAC式的底栏和顶栏': RouteRecordInfo<
      '/posts/MydockFinder MAC式的底栏和顶栏',
      '/posts/MydockFinder%20MAC%E5%BC%8F%E7%9A%84%E5%BA%95%E6%A0%8F%E5%92%8C%E9%A1%B6%E6%A0%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Openlistalist的css美化自用': RouteRecordInfo<
      '/posts/Openlistalist的css美化自用',
      '/posts/Openlistalist%E7%9A%84css%E7%BE%8E%E5%8C%96%E8%87%AA%E7%94%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Valaxy个人博客如何添加一个音乐播放器': RouteRecordInfo<
      '/posts/Valaxy个人博客如何添加一个音乐播放器',
      '/posts/Valaxy%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%E5%A6%82%E4%BD%95%E6%B7%BB%E5%8A%A0%E4%B8%80%E4%B8%AA%E9%9F%B3%E4%B9%90%E6%92%AD%E6%94%BE%E5%99%A8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/VMware25H2下载以及汉化': RouteRecordInfo<
      '/posts/VMware25H2下载以及汉化',
      '/posts/VMware25H2%E4%B8%8B%E8%BD%BD%E4%BB%A5%E5%8F%8A%E6%B1%89%E5%8C%96',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Zero-Typing - 一个美观的打字网站': RouteRecordInfo<
      '/posts/Zero-Typing - 一个美观的打字网站',
      '/posts/Zero-Typing%20-%20%E4%B8%80%E4%B8%AA%E7%BE%8E%E8%A7%82%E7%9A%84%E6%89%93%E5%AD%97%E7%BD%91%E7%AB%99',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/status/': RouteRecordInfo<
      '/status/',
      '/status',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.24_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.27.0_@babel+parser_0e0443622f2d813c9e028549b1bb88ac/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/Bangumi/index.md': {
      routes:
        | '/Bangumi/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'pages/love/index.md': {
      routes:
        | '/love/'
      views:
        | never
    }
    'pages/love/MIKU.md': {
      routes:
        | '/love/MIKU'
      views:
        | never
    }
    'pages/love/Nachoneko.md': {
      routes:
        | '/love/Nachoneko'
      views:
        | never
    }
    'pages/love/SIKADI.md': {
      routes:
        | '/love/SIKADI'
      views:
        | never
    }
    'pages/love/WX.md': {
      routes:
        | '/love/WX'
      views:
        | never
    }
    'pages/love/ZFB.md': {
      routes:
        | '/love/ZFB'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.24_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.24_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/一些咕咕咕JPG.md': {
      routes:
        | '/posts/一些咕咕咕JPG'
      views:
        | never
    }
    'pages/posts/一些DockerCompose配置.md': {
      routes:
        | '/posts/一些DockerCompose配置'
      views:
        | never
    }
    'pages/posts/主板BIOS开机动画更改.md': {
      routes:
        | '/posts/主板BIOS开机动画更改'
      views:
        | never
    }
    'pages/posts/使用Vercount替代不蒜子 - Valaxy.md': {
      routes:
        | '/posts/使用Vercount替代不蒜子 - Valaxy'
      views:
        | never
    }
    'pages/posts/免费VPSClawCloudRun使用3XUI面板进行隧道搭建.md': {
      routes:
        | '/posts/免费VPSClawCloudRun使用3XUI面板进行隧道搭建'
      views:
        | never
    }
    'pages/posts/关于Steam AutoCrack的使用方法.md': {
      routes:
        | '/posts/关于Steam AutoCrack的使用方法'
      views:
        | never
    }
    'pages/posts/域名被运营商阻断而不是被GFWGank.md': {
      routes:
        | '/posts/域名被运营商阻断而不是被GFWGank'
      views:
        | never
    }
    'pages/posts/如何自定义Typora的背景.md': {
      routes:
        | '/posts/如何自定义Typora的背景'
      views:
        | never
    }
    'pages/posts/如何让想要的软件在开机的时候自动启动.md': {
      routes:
        | '/posts/如何让想要的软件在开机的时候自动启动'
      views:
        | never
    }
    'pages/posts/小米手环910 开启心率广播 投屏OBS直播.md': {
      routes:
        | '/posts/小米手环910 开启心率广播 投屏OBS直播'
      views:
        | never
    }
    'pages/posts/小米BE6500开SSH开机自启固化和安装ShellCrash开启全家代理.md': {
      routes:
        | '/posts/小米BE6500开SSH开机自启固化和安装ShellCrash开启全家代理'
      views:
        | never
    }
    'pages/posts/模版.md': {
      routes:
        | '/posts/模版'
      views:
        | never
    }
    'pages/posts/求生之路2之使用FRP反代获得低延迟体验.md': {
      routes:
        | '/posts/求生之路2之使用FRP反代获得低延迟体验'
      views:
        | never
    }
    'pages/posts/流量卡-授人以鱼不如授人以渔.md': {
      routes:
        | '/posts/流量卡-授人以鱼不如授人以渔'
      views:
        | never
    }
    'pages/posts/点读笔-如何在开机时自动启动WIFI热点.md': {
      routes:
        | '/posts/点读笔-如何在开机时自动启动WIFI热点'
      views:
        | never
    }
    'pages/posts/硬件日志.md': {
      routes:
        | '/posts/硬件日志'
      views:
        | never
    }
    'pages/posts/绕过WiFi的Web认证使用3XUI面板搭建隧道FZBZ.md': {
      routes:
        | '/posts/绕过WiFi的Web认证使用3XUI面板搭建隧道FZBZ'
      views:
        | never
    }
    'pages/posts/致命公司自建局域网服务器，反代联机（破解）.md': {
      routes:
        | '/posts/致命公司自建局域网服务器，反代联机（破解）'
      views:
        | never
    }
    'pages/posts/解决npm或pnpm无法更新的问题.md': {
      routes:
        | '/posts/解决npm或pnpm无法更新的问题'
      views:
        | never
    }
    'pages/posts/评论杂烩QAQ.md': {
      routes:
        | '/posts/评论杂烩QAQ'
      views:
        | never
    }
    'pages/posts/需ROOT小米使用FCM(谷歌推送服务).md': {
      routes:
        | '/posts/需ROOT小米使用FCM(谷歌推送服务)'
      views:
        | never
    }
    'pages/posts/BLOG更新日志.md': {
      routes:
        | '/posts/BLOG更新日志'
      views:
        | never
    }
    'pages/posts/BLOG网页部署live2d小人 - 使用Vercount替代不蒜子 - Valaxy.md': {
      routes:
        | '/posts/BLOG网页部署live2d小人 - 使用Vercount替代不蒜子 - Valaxy'
      views:
        | never
    }
    'pages/posts/CentOS配置DNS.md': {
      routes:
        | '/posts/CentOS配置DNS'
      views:
        | never
    }
    'pages/posts/Directory Opus.md': {
      routes:
        | '/posts/Directory Opus'
      views:
        | never
    }
    'pages/posts/Docker的下载安装和使用.md': {
      routes:
        | '/posts/Docker的下载安装和使用'
      views:
        | never
    }
    'pages/posts/Email.md': {
      routes:
        | '/posts/Email'
      views:
        | never
    }
    'pages/posts/FRP配置.md': {
      routes:
        | '/posts/FRP配置'
      views:
        | never
    }
    'pages/posts/FZBZ-F.md': {
      routes:
        | '/posts/FZBZ-F'
      views:
        | never
    }
    'pages/posts/Game.md': {
      routes:
        | '/posts/Game'
      views:
        | never
    }
    'pages/posts/GRUB2配置以及自定义主题以及添加Windows引导.md': {
      routes:
        | '/posts/GRUB2配置以及自定义主题以及添加Windows引导'
      views:
        | never
    }
    'pages/posts/HackBGRT更改Windows开机动画.md': {
      routes:
        | '/posts/HackBGRT更改Windows开机动画'
      views:
        | never
    }
    'pages/posts/Intel MAC使用MAA进行明日方舟挂机.md': {
      routes:
        | '/posts/Intel MAC使用MAA进行明日方舟挂机'
      views:
        | never
    }
    'pages/posts/MarkdownTypora的基本用法与常用操作.md': {
      routes:
        | '/posts/MarkdownTypora的基本用法与常用操作'
      views:
        | never
    }
    'pages/posts/MToolBox 枫の美化工具箱 - Win美化的集大成者.md': {
      routes:
        | '/posts/MToolBox 枫の美化工具箱 - Win美化的集大成者'
      views:
        | never
    }
    'pages/posts/MydockFinder MAC式的底栏和顶栏.md': {
      routes:
        | '/posts/MydockFinder MAC式的底栏和顶栏'
      views:
        | never
    }
    'pages/posts/Openlistalist的css美化自用.md': {
      routes:
        | '/posts/Openlistalist的css美化自用'
      views:
        | never
    }
    'pages/posts/Valaxy个人博客如何添加一个音乐播放器.md': {
      routes:
        | '/posts/Valaxy个人博客如何添加一个音乐播放器'
      views:
        | never
    }
    'pages/posts/VMware25H2下载以及汉化.md': {
      routes:
        | '/posts/VMware25H2下载以及汉化'
      views:
        | never
    }
    'pages/posts/Zero-Typing - 一个美观的打字网站.md': {
      routes:
        | '/posts/Zero-Typing - 一个美观的打字网站'
      views:
        | never
    }
    'pages/status/index.md': {
      routes:
        | '/status/'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
