/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/MIKU': RouteRecordInfo<'/albums/MIKU', '/albums/MIKU', Record<never, never>, Record<never, never>>,
    '/albums/SIKADI': RouteRecordInfo<'/albums/SIKADI', '/albums/SIKADI', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/Bangumi/': RouteRecordInfo<'/Bangumi/', '/Bangumi', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/点读笔-如何在开机时自动启动WIFI热点': RouteRecordInfo<'/posts/点读笔-如何在开机时自动启动WIFI热点', '/posts/点读笔-如何在开机时自动启动WIFI热点', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - 常用命令': RouteRecordInfo<'/posts/咕咕咕 - 常用命令', '/posts/咕咕咕 - 常用命令', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - 希沃': RouteRecordInfo<'/posts/咕咕咕 - 希沃', '/posts/咕咕咕 - 希沃', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - 小米手环': RouteRecordInfo<'/posts/咕咕咕 - 小米手环', '/posts/咕咕咕 - 小米手环', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - 小米Watch1': RouteRecordInfo<'/posts/咕咕咕 - 小米Watch1', '/posts/咕咕咕 - 小米Watch1', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - 子腾手表': RouteRecordInfo<'/posts/咕咕咕 - 子腾手表', '/posts/咕咕咕 - 子腾手表', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - Alist': RouteRecordInfo<'/posts/咕咕咕 - Alist', '/posts/咕咕咕 - Alist', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - Android刷机': RouteRecordInfo<'/posts/咕咕咕 - Android刷机', '/posts/咕咕咕 - Android刷机', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - EasyImage图床': RouteRecordInfo<'/posts/咕咕咕 - EasyImage图床', '/posts/咕咕咕 - EasyImage图床', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - Minecraft服务器': RouteRecordInfo<'/posts/咕咕咕 - Minecraft服务器', '/posts/咕咕咕 - Minecraft服务器', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - OpenWRT配置 copy': RouteRecordInfo<'/posts/咕咕咕 - OpenWRT配置 copy', '/posts/咕咕咕 - OpenWRT配置 copy', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - Windows桌面美化': RouteRecordInfo<'/posts/咕咕咕 - Windows桌面美化', '/posts/咕咕咕 - Windows桌面美化', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - XDF N1': RouteRecordInfo<'/posts/咕咕咕 - XDF N1', '/posts/咕咕咕 - XDF N1', Record<never, never>, Record<never, never>>,
    '/posts/评论杂烩QAQ': RouteRecordInfo<'/posts/评论杂烩QAQ', '/posts/评论杂烩QAQ', Record<never, never>, Record<never, never>>,
    '/posts/致命公司自建局域网服务器，反代联机（破解）': RouteRecordInfo<'/posts/致命公司自建局域网服务器，反代联机（破解）', '/posts/致命公司自建局域网服务器，反代联机（破解）', Record<never, never>, Record<never, never>>,
    '/posts/Email': RouteRecordInfo<'/posts/Email', '/posts/Email', Record<never, never>, Record<never, never>>,
    '/posts/FRP配置': RouteRecordInfo<'/posts/FRP配置', '/posts/FRP配置', Record<never, never>, Record<never, never>>,
    '/posts/FZBZ-Test': RouteRecordInfo<'/posts/FZBZ-Test', '/posts/FZBZ-Test', Record<never, never>, Record<never, never>>,
    '/posts/Game': RouteRecordInfo<'/posts/Game', '/posts/Game', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/Intel MAC使用MAA进行明日方舟挂机': RouteRecordInfo<'/posts/Intel MAC使用MAA进行明日方舟挂机', '/posts/Intel MAC使用MAA进行明日方舟挂机', Record<never, never>, Record<never, never>>,
    '/posts/Zero-Typing - 一个美观的打字网站': RouteRecordInfo<'/posts/Zero-Typing - 一个美观的打字网站', '/posts/Zero-Typing - 一个美观的打字网站', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
