/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/albums/': RouteRecordInfo<'/albums/', '/albums', Record<never, never>, Record<never, never>>,
    '/albums/MIKU': RouteRecordInfo<'/albums/MIKU', '/albums/MIKU', Record<never, never>, Record<never, never>>,
    '/albums/SIKADI': RouteRecordInfo<'/albums/SIKADI', '/albums/SIKADI', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/Bangumi/': RouteRecordInfo<'/Bangumi/', '/Bangumi', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/点读笔-如何在开机时自动启动WIFI热点': RouteRecordInfo<'/posts/点读笔-如何在开机时自动启动WIFI热点', '/posts/点读笔-如何在开机时自动启动WIFI热点', Record<never, never>, Record<never, never>>,
    '/posts/个人BLOG更新更新日志': RouteRecordInfo<'/posts/个人BLOG更新更新日志', '/posts/个人BLOG更新更新日志', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - 常用命令': RouteRecordInfo<'/posts/咕咕咕 - 常用命令', '/posts/咕咕咕 - 常用命令', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - 希沃': RouteRecordInfo<'/posts/咕咕咕 - 希沃', '/posts/咕咕咕 - 希沃', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - 小米手环': RouteRecordInfo<'/posts/咕咕咕 - 小米手环', '/posts/咕咕咕 - 小米手环', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - 小米Watch1': RouteRecordInfo<'/posts/咕咕咕 - 小米Watch1', '/posts/咕咕咕 - 小米Watch1', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - 子腾手表': RouteRecordInfo<'/posts/咕咕咕 - 子腾手表', '/posts/咕咕咕 - 子腾手表', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - Alist': RouteRecordInfo<'/posts/咕咕咕 - Alist', '/posts/咕咕咕 - Alist', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - Android刷机': RouteRecordInfo<'/posts/咕咕咕 - Android刷机', '/posts/咕咕咕 - Android刷机', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - EasyImage图床': RouteRecordInfo<'/posts/咕咕咕 - EasyImage图床', '/posts/咕咕咕 - EasyImage图床', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - Minecraft服务器': RouteRecordInfo<'/posts/咕咕咕 - Minecraft服务器', '/posts/咕咕咕 - Minecraft服务器', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - OpenWRT配置 copy': RouteRecordInfo<'/posts/咕咕咕 - OpenWRT配置 copy', '/posts/咕咕咕 - OpenWRT配置 copy', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - PicList+Github图床': RouteRecordInfo<'/posts/咕咕咕 - PicList+Github图床', '/posts/咕咕咕 - PicList+Github图床', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - Windows桌面美化': RouteRecordInfo<'/posts/咕咕咕 - Windows桌面美化', '/posts/咕咕咕 - Windows桌面美化', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - XDF N1': RouteRecordInfo<'/posts/咕咕咕 - XDF N1', '/posts/咕咕咕 - XDF N1', Record<never, never>, Record<never, never>>,
    '/posts/咕咕咕 - Zen浏览器': RouteRecordInfo<'/posts/咕咕咕 - Zen浏览器', '/posts/咕咕咕 - Zen浏览器', Record<never, never>, Record<never, never>>,
    '/posts/关于Steam AutoCrack的使用方法': RouteRecordInfo<'/posts/关于Steam AutoCrack的使用方法', '/posts/关于Steam AutoCrack的使用方法', Record<never, never>, Record<never, never>>,
    '/posts/解决npm或pnpm无法更新的问题': RouteRecordInfo<'/posts/解决npm或pnpm无法更新的问题', '/posts/解决npm或pnpm无法更新的问题', Record<never, never>, Record<never, never>>,
    '/posts/免费VPSClawCloudRun使用3XUI面板进行隧道搭建': RouteRecordInfo<'/posts/免费VPSClawCloudRun使用3XUI面板进行隧道搭建', '/posts/免费VPSClawCloudRun使用3XUI面板进行隧道搭建', Record<never, never>, Record<never, never>>,
    '/posts/评论杂烩QAQ': RouteRecordInfo<'/posts/评论杂烩QAQ', '/posts/评论杂烩QAQ', Record<never, never>, Record<never, never>>,
    '/posts/求生之路2之使用FRP反代获得低延迟体验': RouteRecordInfo<'/posts/求生之路2之使用FRP反代获得低延迟体验', '/posts/求生之路2之使用FRP反代获得低延迟体验', Record<never, never>, Record<never, never>>,
    '/posts/如何让想要的软件在开机的时候自动启动': RouteRecordInfo<'/posts/如何让想要的软件在开机的时候自动启动', '/posts/如何让想要的软件在开机的时候自动启动', Record<never, never>, Record<never, never>>,
    '/posts/如何自定义Typora的背景': RouteRecordInfo<'/posts/如何自定义Typora的背景', '/posts/如何自定义Typora的背景', Record<never, never>, Record<never, never>>,
    '/posts/使用Vercount替代不蒜子 - Valaxy': RouteRecordInfo<'/posts/使用Vercount替代不蒜子 - Valaxy', '/posts/使用Vercount替代不蒜子 - Valaxy', Record<never, never>, Record<never, never>>,
    '/posts/小米手环910 开启心率广播 投屏OBS直播': RouteRecordInfo<'/posts/小米手环910 开启心率广播 投屏OBS直播', '/posts/小米手环910 开启心率广播 投屏OBS直播', Record<never, never>, Record<never, never>>,
    '/posts/硬件日志': RouteRecordInfo<'/posts/硬件日志', '/posts/硬件日志', Record<never, never>, Record<never, never>>,
    '/posts/致命公司自建局域网服务器，反代联机（破解）': RouteRecordInfo<'/posts/致命公司自建局域网服务器，反代联机（破解）', '/posts/致命公司自建局域网服务器，反代联机（破解）', Record<never, never>, Record<never, never>>,
    '/posts/主板BIOS开机动画更改': RouteRecordInfo<'/posts/主板BIOS开机动画更改', '/posts/主板BIOS开机动画更改', Record<never, never>, Record<never, never>>,
    '/posts/BLOG网页部署live2d小人 - 使用Vercount替代不蒜子 - Valaxy': RouteRecordInfo<'/posts/BLOG网页部署live2d小人 - 使用Vercount替代不蒜子 - Valaxy', '/posts/BLOG网页部署live2d小人 - 使用Vercount替代不蒜子 - Valaxy', Record<never, never>, Record<never, never>>,
    '/posts/CentOS配置DNS': RouteRecordInfo<'/posts/CentOS配置DNS', '/posts/CentOS配置DNS', Record<never, never>, Record<never, never>>,
    '/posts/Directory Opus': RouteRecordInfo<'/posts/Directory Opus', '/posts/Directory Opus', Record<never, never>, Record<never, never>>,
    '/posts/Email': RouteRecordInfo<'/posts/Email', '/posts/Email', Record<never, never>, Record<never, never>>,
    '/posts/FRP配置': RouteRecordInfo<'/posts/FRP配置', '/posts/FRP配置', Record<never, never>, Record<never, never>>,
    '/posts/FZBZ-F': RouteRecordInfo<'/posts/FZBZ-F', '/posts/FZBZ-F', Record<never, never>, Record<never, never>>,
    '/posts/Game': RouteRecordInfo<'/posts/Game', '/posts/Game', Record<never, never>, Record<never, never>>,
    '/posts/GRUB2配置以及自定义主题以及添加Windows引导': RouteRecordInfo<'/posts/GRUB2配置以及自定义主题以及添加Windows引导', '/posts/GRUB2配置以及自定义主题以及添加Windows引导', Record<never, never>, Record<never, never>>,
    '/posts/HackBGRT更改Windows开机动画': RouteRecordInfo<'/posts/HackBGRT更改Windows开机动画', '/posts/HackBGRT更改Windows开机动画', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/Intel MAC使用MAA进行明日方舟挂机': RouteRecordInfo<'/posts/Intel MAC使用MAA进行明日方舟挂机', '/posts/Intel MAC使用MAA进行明日方舟挂机', Record<never, never>, Record<never, never>>,
    '/posts/MarkdownTypora的基本用法与常用操作': RouteRecordInfo<'/posts/MarkdownTypora的基本用法与常用操作', '/posts/MarkdownTypora的基本用法与常用操作', Record<never, never>, Record<never, never>>,
    '/posts/MToolBox 枫の美化工具箱 - Win美化的集大成者': RouteRecordInfo<'/posts/MToolBox 枫の美化工具箱 - Win美化的集大成者', '/posts/MToolBox 枫の美化工具箱 - Win美化的集大成者', Record<never, never>, Record<never, never>>,
    '/posts/MydockFinder MAC式的底栏和顶栏': RouteRecordInfo<'/posts/MydockFinder MAC式的底栏和顶栏', '/posts/MydockFinder MAC式的底栏和顶栏', Record<never, never>, Record<never, never>>,
    '/posts/Valaxy个人博客如何添加一个音乐播放器': RouteRecordInfo<'/posts/Valaxy个人博客如何添加一个音乐播放器', '/posts/Valaxy个人博客如何添加一个音乐播放器', Record<never, never>, Record<never, never>>,
    '/posts/Zero-Typing - 一个美观的打字网站': RouteRecordInfo<'/posts/Zero-Typing - 一个美观的打字网站', '/posts/Zero-Typing - 一个美观的打字网站', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
